### PR TITLE
CC-438 : Changes as per node 18 migration and Dependencies are updated to required version of node 18 build

### PR DESCRIPTION
**Pull request by hselvakumar**
Updates : 

Docker config files are added to have a new way of docker build and run using node 18 shared service image. 
Updated unit test cases and the way constants are declared to match node 18 images.
Updated readme instructions.
Update on vulnerabilities reduced from 7 to 2 up updating few vulnerable package.
Updated dependencies to available versions as below. 

Screenshot 2023-08-16 at 13 48 18

Tested locally 

Screenshot 2023-08-16 at 13 45 50
Screenshot 2023-08-16 at 13 46 44

Clean up's will be done as part of separate ticket

### CODE REVIEW

**Review by sroberts2 — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by sroberts2 — APPROVED** [review]

**Review by mwejuli-ch — APPROVED** [review]

**Pull request merged**
